"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { Areas, Criteria, Plans } from "./modules-admin";
import { AreaOwnerHistory, AreaOwnerIssues, Audit, AuditHistory, AuditorPlan, Issues, Reports } from "./modules-workflow";
type Screen="dashboard"|"areas"|"criteria"|"plans"|"audit"|"history"|"issues"|"resolutions"|"reports";
type Status="Uygun"|"Uygun Değil"|"Bekliyor";
type Row={id:number;category:string;item:string;weight:number;status:Status;note:string;photos:string[]};
type Area={id:string;area_code:string;name:string};
type User={id:string;email:string;fullName:string;role:"admin"|"area_admin"|"auditor"|"area_owner";areas:Area[]};
const menu:[Screen,string,string][]=[["dashboard","Genel Bakış","⌂"],["areas","Alan & QR Yönetimi","▦"],["criteria","Kriter Yönetimi","☷"],["plans","Tetkik Planlama","◷"],["audit","QR ile Tetkik","✓"],["history","Geçmiş Tetkiklerim","▥"],["issues","Düzeltme Görevlerim","!"],["resolutions","Geçmiş Belgelemelerim","▥"],["reports","Raporlar","▥"]];
const seedRows:Row[]=[
 {id:1,category:"Ayıklama",item:"Gereksiz malzeme ve ekipman çalışma alanından uzaklaştırılmıştır.",weight:15,status:"Uygun",note:"",photos:[]},
 {id:2,category:"Düzenleme",item:"Malzemelerin tanımlı yerleri ve görsel işaretlemeleri mevcuttur.",weight:15,status:"Uygun Değil",note:"Yedek merdane alanında zemin işaretleri silinmiş.",photos:[]},
 {id:3,category:"Temizlik",item:"Zemin, makine ve ekipmanlar temiz durumdadır.",weight:20,status:"Uygun",note:"",photos:[]},
 {id:4,category:"Standartlaştırma",item:"5S standartları ve kontrol listeleri günceldir.",weight:20,status:"Uygun Değil",note:"Panoda kriter tablosunun eski sürümü bulunuyor.",photos:[]},
 {id:5,category:"Disiplin",item:"Tanımlı 5S kuralları çalışanlar tarafından uygulanmaktadır.",weight:20,status:"Uygun",note:"",photos:[]},
 {id:6,category:"İSG",item:"Yürüyüş yolları ve acil çıkışlar açık durumdadır.",weight:10,status:"Bekliyor",note:"",photos:[]},
];
const factor:Record<Status,number>={Uygun:1,"Uygun Değil":0,Bekliyor:0};
const API_BASE=process.env.NEXT_PUBLIC_API_BASE_URL||"http://localhost:4000";
const areas=[{no:"A-01",name:"Sıcak Haddehane",sub:"Merdane Hazırlama",owner:"Ahmet Demir",status:"Aktif"},{no:"A-02",name:"Çelikhane",sub:"Konverter Bölgesi",owner:"Selin Arslan",status:"Aktif"},{no:"A-03",name:"Soğuk Haddehane",sub:"Paketleme",owner:"Murat Şahin",status:"Aktif"},{no:"A-04",name:"Merkez Laboratuvar",sub:"Numune Hazırlama",owner:"Ece Kaya",status:"Pasif"}];
function Logo(){return <div className="logo"><img src="/erdemir-logo.png" alt="Erdemir"/><span>Dijital 5S Tetkik Sistemi</span></div>}
function Qr({cells}:{cells:boolean[]}){return <div className="qr">{cells.map((on,i)=><i key={i} className={on?"on":""}/>)}</div>}

export default function Home(){
 const[user,setUser]=useState<User|null>(null),[token,setToken]=useState(""),[screen,setScreen]=useState<Screen>("dashboard"),[rows,setRows]=useState(seedRows),[active,setActive]=useState<number|null>(null),[qr,setQr]=useState(false),[qrName,setQrName]=useState("Sıcak Haddehane"),[search,setSearch]=useState(""),[notice,setNotice]=useState(3),[noticeOpen,setNoticeOpen]=useState(false),[planPublished,setPlanPublished]=useState(false),[issueState,setIssueState]=useState("Düzeltme Bekliyor"),[saveState,setSaveState]=useState("Kaydet");
 const file=useRef<HTMLInputElement>(null),score=Math.round(rows.reduce((a,r)=>a+r.weight*factor[r.status],0)),done=rows.filter(r=>r.status!=="Bekliyor").length,selected=rows.find(r=>r.id===active);
 const authHeaders={Authorization:`Bearer ${token}`};
 const update=(id:number,p:Partial<Row>)=>setRows(rs=>rs.map(r=>r.id===id?{...r,...p}:r));
 const addPhotos=async(f:FileList|null)=>{if(!f||active===null)return;const urls:string[]=[];for(const photo of Array.from(f)){const form=new FormData();form.set("file",photo);form.set("criterionId",String(active));const response=await fetch(`${API_BASE}/api/evidence`,{method:"POST",headers:authHeaders,body:form});if(response.ok)urls.push((await response.json()).url)}update(active,{photos:[...(selected?.photos||[]),...urls]})};
 const persist=async()=>{setSaveState("Kaydediliyor...");try{const response=await fetch(`${API_BASE}/api/audits/current`,{method:"POST",headers:{...authHeaders,"content-type":"application/json"},body:JSON.stringify({rows,score,issueState,planPublished})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Kayıt başarısız");setSaveState("✓ PostgreSQL'e kaydedildi")}catch(error){setSaveState(error instanceof Error?error.message:"Kayıt başarısız")}setTimeout(()=>setSaveState("Kaydet"),3500)};
 useEffect(()=>{if(!user||user.role!=="auditor")return;fetch(`${API_BASE}/api/audits/current`,{headers:authHeaders}).then(r=>r.ok?r.json():null).then(data=>{const saved=data?.audit?.payload;if(saved?.rows)setRows(saved.rows);if(saved?.issueState)setIssueState(saved.issueState);if(typeof saved?.planPublished==="boolean")setPlanPublished(saved.planPublished)}).catch(()=>undefined)},[user,token]);
 const cells=useMemo(()=>Array.from({length:441},(_,i)=>{const x=i%21,y=Math.floor(i/21),finder=(a:number,b:number)=>x>=a&&x<a+7&&y>=b&&y<b+7&&(x===a||x===a+6||y===b||y===b+6||(x>=a+2&&x<=a+4&&y>=b+2&&y<=b+4));return finder(0,0)||finder(14,0)||finder(0,14)||((i*13+x*y+142)%7<3)}),[]);
 if(!user)return <Login enter={(u,t)=>{setUser(u);setToken(t);setScreen(u.role==="auditor"?"audit":u.role==="area_owner"?"issues":"dashboard")}}/>;
 const roleLabel=user.role==="admin"?"Global Sistem Yöneticisi":user.role==="area_admin"?"Müdürlük Yöneticisi":user.role==="area_owner"?"Alan Sorumlusu":"Tetkikçi";
 const allowed=user.role==="admin"?menu.filter(([id])=>!["history","resolutions"].includes(id)):menu.filter(([id])=>(user.role==="area_admin"?["dashboard","criteria","plans","reports"]:user.role==="auditor"?["plans","audit","history"]:["issues","resolutions"]).includes(id));
 return <main className="system-shell"><Sidebar allowed={allowed} screen={screen} user={user} role={roleLabel} go={setScreen} logout={()=>{setUser(null);setToken("")}}/><section className="content"><header className="system-top"><span>{menu.find(m=>m[0]===screen)?.[1]}</span><div className="top-actions">{user.role==="auditor"&&<button className="db-save" onClick={persist}>{saveState}</button>}<button className="bell" aria-label="Bildirimler" onClick={()=>setNoticeOpen(v=>!v)}>♢{notice>0&&<b>{notice}</b>}</button>{noticeOpen&&<NotificationPanel role={user.role} area={user.areas[0]?.name} close={()=>setNoticeOpen(false)} readAll={()=>setNotice(0)} go={s=>{setScreen(s);setNoticeOpen(false)}}/>}</div></header><div className="module">{screen==="dashboard"&&<Dashboard go={setScreen}/>} {screen==="areas"&&<Areas token={token} openQr={n=>{setQrName(n);setQr(true)}}/>} {screen==="criteria"&&<Criteria token={token} user={user}/>} {screen==="plans"&&(user.role==="auditor"?<AuditorPlan api={API_BASE} token={token}/>:<Plans token={token}/>)} {screen==="audit"&&<Audit rows={rows} score={score} done={done} search={search} setSearch={setSearch} update={update} openEvidence={setActive} openQr={()=>{setQrName("Sıcak Haddehane / Merdane Hazırlama");setQr(true)}} save={persist} saveState={saveState}/>} {screen==="history"&&<AuditHistory api={API_BASE} token={token}/>} {screen==="issues"&&(user.role==="area_owner"?<AreaOwnerIssues api={API_BASE} token={token}/>:<Issues state={issueState} setState={setIssueState}/>)} {screen==="resolutions"&&<AreaOwnerHistory api={API_BASE} token={token}/>} {screen==="reports"&&<Reports/>}</div></section>
 <Evidence selected={selected} file={file} update={update} addPhotos={addPhotos} close={()=>setActive(null)}/>{qr&&<QrModal name={qrName} cells={cells} close={()=>setQr(false)}/>}</main>
}
function NotificationPanel({role,area,close,readAll,go}:{role:User["role"];area?:string;close:()=>void;readAll:()=>void;go:(s:Screen)=>void}){const items=role==="area_owner"?[{icon:"!",title:"Düzeltme görevi atandı",text:`${area||"Sorumlu alan"} · Uygunsuzluğu giderin`,time:"Bugün · 17:00",screen:"issues" as Screen},{icon:"📷",title:"Giderme kanıtı bekleniyor",text:"Açıklama ve sonrası fotoğrafı ekleyin",time:"2 saat önce",screen:"issues" as Screen},{icon:"◷",title:"Düzeltme son tarihi yaklaşıyor",text:"Açık görevi son tarihten önce tamamlayın",time:"Yarın",screen:"issues" as Screen}]:role==="auditor"?[{icon:"◷",title:"Tetkik son tarihi yaklaşıyor",text:`${area||"Atanmış alan"} tetkikini tamamlayın`,time:"Yarın · 16:30",screen:"audit" as Screen},{icon:"📷",title:"Fotoğraf kanıtı eksik",text:"Uygun değil sonucu için kanıt ekleyin",time:"Bugün",screen:"audit" as Screen},{icon:"✓",title:"Yeni tetkik görevi",text:"Aylık 5S kontrol listesi atandı",time:"3 saat önce",screen:"audit" as Screen}]:[{icon:"!",title:"2 gecikmiş uygunsuzluk",text:"Alan sorumlularının düzeltmeleri bekleniyor",time:"Bugün",screen:"issues" as Screen},{icon:"◷",title:"Tetkik planı yayımlanacak",text:"Tetkikçi atamalarını kontrol edin",time:"Yarın",screen:"plans" as Screen},{icon:"☷",title:"3 kriter onay bekliyor",text:"Alan bazlı taslak kriterler hazır",time:"Dün",screen:"criteria" as Screen}];return <aside className="notification-panel"><div className="notification-head"><div><span>BİLDİRİMLER</span><h3>Bekleyen işler</h3></div><button onClick={close}>×</button></div><div className="notification-list">{items.map((n,i)=><button key={i} onClick={()=>go(n.screen)}><i>{n.icon}</i><span><b>{n.title}</b><small>{n.text}</small><em>{n.time}</em></span></button>)}</div><button className="read-all" onClick={readAll}>Tümünü okundu işaretle</button></aside>}
function PageTitle({tag,title,text,action}:{tag:string,title:string,text:string,action?:React.ReactNode}){return <div className="module-title"><div><span className="eyebrow">{tag}</span><h1>{title}</h1><p>{text}</p></div>{action}</div>}
function Login({enter}:{enter:(u:User,t:string)=>void}){const[email,setEmail]=useState("admin@erdemir.com.tr"),[password,setPassword]=useState("12345678"),[error,setError]=useState(""),[busy,setBusy]=useState(false);const submit=async()=>{setBusy(true);setError("");try{const r=await fetch(`${API_BASE}/api/auth/login`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw new Error(d.error);enter(d.user,d.token)}catch(e){setError(e instanceof Error?e.message:"Giriş başarısız")}finally{setBusy(false)}};return <main className="login"><section className="login-visual"><div className="login-copy"><span>ERDEMİR · DİJİTAL OPERASYON</span><h1>5S’i sahada yönet,<br/>sonucu anında gör.</h1><p>Planlamadan düzeltici faaliyet onayına kadar tüm 5S tetkik süreci tek merkezde.</p></div></section><section className="login-panel"><Logo/><div className="login-box"><span className="eyebrow">GÜVENLİ KURUMSAL ERİŞİM</span><h2>Tekrar hoş geldiniz</h2><p>Rolünüz ve erişebileceğiniz alanlar hesabınızdan belirlenir.</p><label>Kullanıcı adı veya e-posta<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Şifre<input type="password" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>e.key==="Enter"&&submit()}/></label>{error&&<p className="danger-text">{error}</p>}<button className="primary wide" disabled={busy} onClick={submit}>{busy?"Giriş yapılıyor...":"Giriş yap"}<b>→</b></button><small className="secure">▣ Rol ve alan bazlı güvenli erişim</small></div></section></main>}
function Sidebar({allowed,screen,user,role,go,logout}:{allowed:[Screen,string,string][],screen:Screen,user:User,role:string,go:(s:Screen)=>void,logout:()=>void}){const initials=user.fullName.split(" ").map(x=>x[0]).join("").slice(0,2);return <aside className="sidebar"><Logo/><div className="role"><span>{initials}</span><div><b>{user.fullName}</b><small>{role}</small></div></div><nav>{allowed.map(([id,label,icon])=><button key={id} className={screen===id?"active":""} onClick={()=>go(id)}><i>{icon}</i>{label}{id==="issues"&&<em>2</em>}</button>)}</nav><div className="side-bottom"><button onClick={logout}>↪ Çıkış yap</button><small>5S Sistem · v1.0</small></div></aside>}
function Evidence({selected,file,update,addPhotos,close}:{selected:Row|undefined,file:React.RefObject<HTMLInputElement|null>,update:(id:number,p:Partial<Row>)=>void,addPhotos:(f:FileList|null)=>void,close:()=>void}){if(!selected)return null;return <div className="overlay" onMouseDown={close}><aside onMouseDown={e=>e.stopPropagation()}><div className="side-head"><div><span className="eyebrow">KRİTER {String(selected.id).padStart(2,"0")}</span><h2>Uygunsuzluk ve kanıt</h2></div><button onClick={close}>×</button></div><p className="criterion">{selected.item}</p><label className="field">Değerlendirme<select value={selected.status} onChange={e=>update(selected.id,{status:e.target.value as Status})}><option>Bekliyor</option><option>Uygun</option><option>Uygun Değil</option></select></label><label className="field">Uygunsuzluk açıklaması<textarea value={selected.note} onChange={e=>update(selected.id,{note:e.target.value})}/></label><label className="field">Zorunlu fotoğraf kanıtı<button className="camera" onClick={()=>file.current?.click()}><b>📷</b><strong>Fotoğraf çek veya yükle</strong><small>Mobil kamera desteklenir · JPG, PNG</small></button><input ref={file} hidden type="file" accept="image/*" capture="environment" multiple onChange={e=>addPhotos(e.target.files)}/></label><div className="side-actions"><button className="outline" onClick={close}>Vazgeç</button><button className="primary" disabled={selected.status==="Uygun Değil"&&selected.photos.length===0} onClick={close}>Kanıtı kaydet</button></div></aside></div>}
function QrModal({name,cells,close}:{name:string,cells:boolean[],close:()=>void}){return <div className="overlay modal-wrap" onMouseDown={close}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="x" onClick={close}>×</button><span className="eyebrow">BENZERSİZ ALAN QR KODU</span><h2>{name}</h2><p>Okutulduğunda alanın aktif kriter tablosu açılır.</p><Qr cells={cells}/><b>ERD-5S-A01-2026</b><div className="modal-actions"><button className="outline" onClick={()=>window.print()}>Yazdır</button><button className="primary" onClick={()=>alert("QR kodu cihaza indirildi.")}>Cihaza indir</button></div></div></div>}
function Dashboard({go}:{go:(s:Screen)=>void}){return <><PageTitle tag="19 AĞUSTOS 2026 · ÇARŞAMBA" title="5S Yönetim Merkezi" text="Tüm alanların güncel durumu ve bekleyen işlemler." action={<button className="primary" onClick={()=>go("plans")}>＋ Yeni tetkik planı</button>}/><div className="kpis"><article><small>GENEL 5S PUANI</small><b>86,4</b><em className="up">↑ 3,2 puan</em></article><article><small>AKTİF TETKİK</small><b>12</b><em>4’ü bugün</em></article><article><small>AÇIK UYGUNSUZLUK</small><b>7</b><em className="danger-text">2 gecikmiş</em></article><article><small>ONAY BEKLEYEN</small><b>3</b><em>Düzeltici faaliyet</em></article></div><div className="dashboard-grid"><section className="panel"><div className="panel-head"><div><h3>Alan performansı</h3><p>Son tamamlanan tetkik puanları</p></div><button onClick={()=>go("reports")}>Tüm raporlar →</button></div>{[["Sıcak Haddehane",91],["Çelikhane",84],["Soğuk Haddehane",78],["Merkez Laboratuvar",94]].map(([n,v])=><div className="bar-row" key={String(n)}><span>{n}</span><div><i style={{width:`${v}%`}}/></div><b>{v}</b></div>)}</section><section className="panel activity"><div className="panel-head"><div><h3>Bekleyen işlemler</h3><p>Öncelik sırasına göre</p></div></div><button onClick={()=>go("issues")}><i className="urgent">!</i><span><b>2 uygunsuzluk gecikti</b><small>Sıcak Haddehane</small></span><em>İncele →</em></button><button onClick={()=>go("plans")}><i>◷</i><span><b>Ağustos planı yayımlanacak</b><small>8 tetkikçi atanmayı bekliyor</small></span><em>Planla →</em></button><button onClick={()=>go("criteria")}><i>☷</i><span><b>Kriter v3.2 taslakta</b><small>5 değişiklik onay bekliyor</small></span><em>Aç →</em></button></section></div></>}
