"use client";
import { useState } from "react";
type Role = "admin" | "area_admin" | "auditor" | "area_owner";
const deck = "/training/5S-2023-Bilgilendirme-Sunumu.pptx";
const roleNames: Record<Role,string> = { admin: "Global Admin", area_admin: "Ünite Sorumlusu", auditor: "Tetkikçi", area_owner: "Alan Sorumlusu" };
const steps: Record<Role,string[]> = {
 admin: ["Tetkik Planlama ekranında bekleyen kriter ve görevli paketini inceleyip onaylayın.","Düzeltme Onayları bölümünden gönderilen kanıtları inceleyin.","Raporlar bölümünden tüm ünitelerin sonuçlarını izleyin."],
 area_admin: ["İlgili alan ve ay için kriterleri hazırlayın.","Tetkikçi ile alan sorumlusunu seçip admin onayına gönderin.","Ünitenizin düzeltme ve rapor kayıtlarını takip edin."],
 auditor: ["Size atanan ve onaylanan planı açın.","Her kriteri Uygun veya Uygun Değil olarak değerlendirin.","Uygunsuzlukta açıklama ve fotoğraf ekleyip tetkiki tamamlayın."],
 area_owner: ["Atanan uygunsuzluğu ve tetkikçi fotoğrafını inceleyin.","Açıklama ve sonrası fotoğrafını ekleyin.","Onaya gönderip sonucu Geçmiş Belgelemelerim bölümünden takip edin."]
};
export function Training(){const[slide,setSlide]=useState(1);return <><header className="learning-title"><span>EĞİTİM / BİLGİLENDİRME</span><h1>5S eğitim merkezi</h1><p>5S adımlarını, sorumlulukları ve denetim prensiplerini inceleyin.</p></header><section className="learning-actions"><div><h2>5S 2023 Bilgilendirme Sunumu</h2><p>18 slayt · uygulama prensipleri, sorumluluklar ve denetim yaklaşımı</p></div><div><a className="outline" href={deck} target="_blank" rel="noreferrer">Sunumu aç</a><a className="primary" href={deck} download>PowerPoint’i indir</a></div></section><section className="training-viewer"><div className="training-stage"><img src={`/training/5S-2023-Bilgilendirme-Sunumu/slide-${slide}.png`} alt={`5S eğitim sunumu ${slide}. slayt`}/><div><button className="outline" disabled={slide===1} onClick={()=>setSlide(s=>s-1)}>← Önceki</button><b>{slide} / 18</b><button className="outline" disabled={slide===18} onClick={()=>setSlide(s=>s+1)}>Sonraki →</button></div></div><aside><h3>Sunum içeriği</h3>{[[3,"Sorumluluklar"],[6,"Ayıklama"],[7,"Düzen"],[9,"Temizlik"],[10,"Standartlaştırma"],[11,"Disiplin"],[14,"Denetim ve değerlendirme"]].map(([n,t])=><button key={n} onClick={()=>setSlide(Number(n))}>{t}</button>)}</aside></section></>}
export function Help({role}:{role:Role}){return <><header className="learning-title"><span>YARDIM</span><h1>Uygulama nasıl kullanılır?</h1><p>Oturumunuz: <b>{roleNames[role]}</b>. Adımlar rolünüze göre gösterilmektedir.</p></header><section className="help-flow">{steps[role].map((text,index)=><article key={text}><i>{index+1}</i><div><h3>{index===0?"Başlayın":index===2?"Sonucu takip edin":"İşlemi tamamlayın"}</h3><p>{text}</p></div></article>)}</section><section className="panel help-notes"><h2>Genel kullanım bilgileri</h2><div><p><b>Bildirimler:</b> Sağ üstteki zil yeni görevleri ve onayları gösterir.</p><p><b>Fotoğraf:</b> JPG veya PNG kullanın ve yükleme tamamlanmadan kaydetmeyin.</p><p><b>Yetki:</b> Alanlar hesabınızın rolü ve bağlı ünitesiyle sınırlandırılır.</p><p><b>QR:</b> Tetkikçi alan QR kodunu okutarak tetkik ekranına geçer.</p></div></section></>}
